//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAlytalosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaloSauna
    {
        public int SaunaId { get; set; }
        public Nullable<int> TaloId { get; set; }
        public string SaunaNimi { get; set; }
        public Nullable<int> SaunaNykyLampotila { get; set; }
        public bool SaunaTila { get; set; }
    
        public virtual Talot Talot { get; set; }
    }
}
