//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAlytalosovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaloLampo
    {
        public int LampoId { get; set; }
        public int TaloId { get; set; }
        public string Huone { get; set; }
        public Nullable<int> HuoneTavoiteLampotila { get; set; }
        public int HuoneNykyLampotila { get; set; }
    
        public virtual Talot Talot { get; set; }
    }
}
